name: qr_code_scan
description: "A QR Code scanner sample."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  qr_flutter: ^4.1.0
  qr_code_scanner: ^1.0.1
  mockito: ^5.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  test: ^1.25.2

flutter:

  uses-material-design: true